# Generated by Django 4.1.7 on 2023-04-04 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TS", "Танки"),
                            ("HL", "Хиллы"),
                            ("MH", "Торговцы"),
                            ("DD", "ДД"),
                            ("GM", "Гилдмастеры"),
                            ("QG", "Квестгиверы"),
                            ("BS", "Кузнецы"),
                            ("TR", "Кожевники"),
                            ("PM", "Зельевары"),
                            ("SM", "Мастера заклинаний"),
                            ("GM", "Гилдмастеры"),
                        ],
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("text", froala_editor.fields.FroalaField()),
                ("timeCreation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "response_status",
                    models.CharField(
                        choices=[("RV", "Принято"), ("UR", "Не принято")],
                        default="UR",
                        max_length=2,
                    ),
                ),
                ("timeCreation", models.DateTimeField(auto_now_add=True)),
                (
                    "responseAdvert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ads.advert"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ads.author"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advert",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ads.author"
            ),
        ),
    ]
