# Generated by Django 4.1.7 on 2023-04-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_advert_upload_alter_advert_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="response_status",
            field=models.BooleanField(default=False),
        ),
    ]
