# Generated by Django 4.1.7 on 2023-04-07 13:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_alter_response_response_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="advert", name="upload",),
        migrations.AlterField(
            model_name="advert",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
