# Generated by Django 4.1.7 on 2023-04-11 12:09

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_remove_advert_upload_alter_advert_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert", name="text", field=froala_editor.fields.FroalaField(),
        ),
    ]
