# Generated by Django 4.1.7 on 2023-04-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0008_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
